language: ruby
rvm:
  - 2.3.3
addons:
  postgresql: '9.4'
services:
  - postgresql
before_install: gem install bundler -v 1.13.6
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
