default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mentions_development

test:
  <<: *default
  database: mentions_test

production:
  <<: *default
  database: mentions_production
  username: mentions
  password: <%= ENV['MENTIONS_DATABASE_PASSWORD'] %>
